BUG: We need a Renderer for HasTranslucentPolygonalGeometry
Without this fix vtkCaptionRepresentationTest1 would print
the following errors:
ERROR: In Rendering/Core/vtkCoordinate.cxx, line 351
vtkCoordinate (0x7ffdbac2a3a0): Request for coordinate transformation without required viewport