BUG: Fix test volume of interest to match data extents
This fixes the following message issued by this test

ERROR: In vtkStreamingDemandDrivenPipeline.cxx, line 857
vtkCompositeDataPipeline (0x21589b0): The update extent specified in the information for output port 0 on algorithm vtkVolume16Reader(0x294b7b0) is 32 32 0 63 0 93, which is outside the whole extent 0 63 0 63 0 92.