Fix types for VTK_USE_64BIT_IDS in vtkPParticleTracerBase
Use vtkIdType instead of int where needed. This addresses compilation errors such as:
vtkPParticleTracerBase.cxx:295:36: error: no matching function for call to 'vtkMPICommunicator::AllGatherV(char*, char*, int&, int*, int*)'

Change-Id: I3ced053aba3dd234d1af92e025d7191cd45ce2ab