OpenGL2: Fix undeclared "glXGetProcAddressARB" when building on Centos5
This commit fixes the build error reported below when building VTK
on Centos 5.11 where mesa 6.5.1 is used.

Not that the compiler used is a newer version of g++ with c++11 support.
See [1]


  VTK/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx:581:76: error: ‘glXGetProcAddressARB’ was not declared in this scope
       glXGetProcAddressARB( (const GLubyte *) "glXCreateContextAttribsARB" );

[1] https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/html/2.0_Release_Notes/DTS2.0_Release.html