Tentative fix for Windows build issue.
1) error: '_snprintf_s' was not declared in this scope;

2) warning: operator[] for vtkStdString is ambiguos when used with
an integral literal index, because of the const char* conversion
operator.

Change-Id: I42b878078277b91509d8d24bbbcaf82aa08eb2a3