vtkMersenneTwister: Work around NULL conversion error on VS 2010
VS 2010 fails to compile vtkMersenneTwister with:

    error C2440: 'initializing' : cannot convert from 'int' to 'mt_struct *'

It is unclear why it fails to convert `NULL` (which expands to `0`) to
a null pointer.  Work around the problem with an explicit cast.